PUT http://localhost:3000/api/contacts/64bb8d3d59f9b77fb85cd48e
Content-Type: application/json

{
    "newName" : "Kemal",
    "newPhoneNumber" : "081598765423"
}

###
GET http://localhost:3000/api/contacts/